theme: minima
baseurl: "/ooc"

google_analytics: G-MGR2S8P4HV

markdown: kramdown

collections:
  chapters:
    output: true
    permalink: /novels/:path/

defaults:
  - scope:
      path: "_chapters"
      type: "chapters"
    values:
      layout: "chapter"
