name: Update front matter
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is available

      - name: Update front matter
        run: |
          if [ -d "_chapters" ]; then
            find _chapters -type f -name "*.md" | while read file; do
              created_at=$(git log --diff-filter=A --format="%ad" --date=iso -- "$file" | tail -n 1)

              if [ -z "$created_at" ]; then
                created_at="Unknown"  # Fallback if creation date can't be determined
              fi

              if awk '/^---$/{i++} i==2{exit} END{exit (i!=2)}' "$file"; then
                # File has front matter, update or insert created_at
                awk -v date="$created_at" '
                BEGIN {inside=0}
                /^---$/ {inside++; if (inside==2) print "created_at: \"" date "\""}
                !/^created_at:/ {print}
                ' "$file" > temp.md && mv temp.md "$file"
              else
                # Extract first heading as title
                title=$(grep -m 1 '^# ' "$file" | sed 's/^# //')

                # If no title found, use filename as fallback
                [ -z "$title" ] && title="$(basename "$file" .md)"

                # Prepend new front matter
                {
                  echo "---"
                  echo "title: \"$title\""
                  echo "created_at: \"$created_at\""
                  echo "---"
                  cat "$file"
                } > temp.md && mv temp.md "$file"
              fi
            done

            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions@github.com"
            git diff --quiet || (git add _chapters && git commit -m "Update front matter" && git push)
          fi
